import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
const inter = Inter({ subsets: ['latin'] })

import { headers } from 'next/headers';
import ContextProvider from '@/context'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const headersList = await headers();
  const cookies = headersList.get('cookie');
  return (
    <html lang="en">
      <body
        className={`${inter} ${inter} antialiased`}
      >
        <ContextProvider cookies={cookies}>{children}</ContextProvider>
      </body>
    </html>
  );
}
